output_dir: "outputs"
model_name: "test1"
data_path: "../data"
device: "cpu"
method: "genetic" # or sgd or with svm
evaluate: True
shape_list: [784, 20, 10 , 5]
batch_size: 32
# genetic params
pop_size: 10 
generations: 0
# finetune params (using with genetic)
finetune_epoch: 1
finetune_lr: 0.01
# sgd params
epochs: 1
lr: 0.05
